import Head from 'next/head'
import React from 'react'
import Confirm_location from '../../Components/ConfirmLocation'
import Layout from '../../Components/Layout'

function ConfirmLocation() {

  return (
    <>
      <Head>
        <title>Confirm Location</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Layout>
        <div className="confirmLocation " >
      <Confirm_location/>
        </div>
      </Layout>
    </>
  )
}

export default ConfirmLocation;