import Head from 'next/head'
import About from '../Components/About';
// import { Button } from 'react-bootstrap';
import Banner from '../Components/Banner';
import BookNow from '../Components/BookNow';
import Layout from '../Components/Layout';
import Loder from '../Components/Loder';
import Pricing from '../Components/Pricing';
import Services from '../Components/Services';
import Testimonials from '../Components/Testimonials';
import styles from '../styles/Home.module.css'

export default function Home()
{

  return (
    <div className={styles.container}>
      <Head>
        <title>The Urban Car Wash | Home</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Layout>

        <div className="banner">
          <Banner />
        </div>
        <div className="Bookings mb-[100px] md:mt-28 mt-14">
          <BookNow props={{ cross: false }} />
        </div>
        <div className="about md:mb-[140px] mb-[90px]">
          <About />
        </div>
        <div className="services-pricing w-[100%] bg-black pb-12  mb-14">
          <Services />
          <div className="pricing md:mt-[140px] mt-[90px]">
            <Pricing />
          </div>
        </div>
        <div className="testimonial mb-8">
          <Testimonials />
        </div>

      </Layout>

    </div>
  )
}
